# Build Plugin.Maui.Intercom on Windows (Android flavor).
#
# The plugin consumes the Android binding as a NuGet package, not a project reference, so a
# source change to src/android/native has to be packed before the plugin can see it. This
# script does that: pack the binding into a local feed, then restore the plugin against it.
#
# The iOS binding (src/macios/Intercom.iOS.Binding) is generated by swift-dotnet-bindings and
# can only build on macOS with Xcode 26+ — use eng/generate-ios-binding.sh there. Rather than
# point restore at an already-published iOS binding (which no longer works: the plugin now
# also targets net9.0-ios, and no published version carries that asset yet), this narrows the
# plugin and the sample to their Android target frameworks. Both net9 and net10 are built —
# a net9-only break is exactly the kind of thing a net10-only local build would hide.

$ErrorActionPreference = 'Stop'

# Narrow the TFM matrix for this machine. Environment variables, not -p:, because a
# semicolon-separated property value does not survive the MSBuild command line.
$env:IntercomPluginTargetFrameworks = 'net9.0-android;net10.0-android'
$env:IntercomSampleTargetFrameworks = 'net10.0-android'

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$feed = Join-Path $scriptPath 'artifacts\local-feed'
$config = Join-Path $scriptPath 'nuget.local.config'

Write-Host "Building Plugin.Maui.Intercom..." -ForegroundColor Cyan
Write-Host ""

Push-Location $scriptPath
try {
    Write-Host "[1/4] Packing Android Binding into the local feed..." -ForegroundColor Yellow
    dotnet pack "src\android\Intercom.Android.Binding\Intercom.Android.Binding.csproj" -c Release -o $feed
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Android Binding pack failed" -ForegroundColor Red
        exit 1
    }

    Write-Host "[2/4] Writing $config..." -ForegroundColor Yellow
    @"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="local" value="artifacts/local-feed" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
"@ | Set-Content -Path $config -Encoding utf8

    Write-Host "[3/4] Building Main Library (net9.0-android + net10.0-android)..." -ForegroundColor Yellow
    dotnet build "src\Plugin.Maui.Intercom\Plugin.Maui.Intercom.csproj" -c Release --configfile $config
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Main Library build failed" -ForegroundColor Red
        exit 1
    }

    Write-Host "[4/4] Building Sample App (net10.0-android)..." -ForegroundColor Yellow
    dotnet build "src\sample\MauiSample.csproj" -c Release -f net10.0-android --configfile $config
    if ($LASTEXITCODE -ne 0) {
        Write-Host "WARNING: Sample App build had issues" -ForegroundColor Yellow
    }

    Write-Host ""
    Write-Host "Build Complete!" -ForegroundColor Green
} finally {
    Pop-Location
}
