# Build Plugin.Maui.Intercom on Windows (Android flavor).
#
# The plugin consumes the Android binding as a NuGet package, not a project reference, so a
# source change to src/android/native has to be packed before the plugin can see it. This
# script does that: pack the binding into a local feed, then restore the plugin against it.
#
# The iOS binding (src/macios/Intercom.iOS.Binding) is generated by swift-dotnet-bindings and
# can only build on macOS with Xcode 26+ — use eng/generate-ios-binding.sh there. Since it
# cannot be produced here at the current version, restore is pointed at an already-published
# version via IntercomIosBindingVersion purely so that resolution succeeds; only the Android
# target framework is actually built.

$ErrorActionPreference = 'Stop'

# Last published Plugin.Maui.Intercom.iOS.Binding. Only used to satisfy restore on Windows.
$iosBindingFallback = '0.8.1'

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$feed = Join-Path $scriptPath 'artifacts\local-feed'
$config = Join-Path $scriptPath 'nuget.local.config'

Write-Host "Building Plugin.Maui.Intercom..." -ForegroundColor Cyan
Write-Host ""

Push-Location $scriptPath
try {
    Write-Host "[1/4] Packing Android Binding into the local feed..." -ForegroundColor Yellow
    dotnet pack "src\android\Intercom.Android.Binding\Intercom.Android.Binding.csproj" -c Release -o $feed
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Android Binding pack failed" -ForegroundColor Red
        exit 1
    }

    Write-Host "[2/4] Writing $config..." -ForegroundColor Yellow
    @"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="local" value="artifacts/local-feed" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
"@ | Set-Content -Path $config -Encoding utf8

    Write-Host "[3/4] Building Main Library (net10.0-android)..." -ForegroundColor Yellow
    dotnet build "src\Plugin.Maui.Intercom\Plugin.Maui.Intercom.csproj" -c Release -f net10.0-android `
        --configfile $config -p:IntercomIosBindingVersion=$iosBindingFallback
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Main Library build failed" -ForegroundColor Red
        exit 1
    }

    Write-Host "[4/4] Building Sample App (net10.0-android)..." -ForegroundColor Yellow
    dotnet build "src\sample\MauiSample.csproj" -c Release -f net10.0-android `
        --configfile $config -p:IntercomIosBindingVersion=$iosBindingFallback
    if ($LASTEXITCODE -ne 0) {
        Write-Host "WARNING: Sample App build had issues" -ForegroundColor Yellow
    }

    Write-Host ""
    Write-Host "Build Complete!" -ForegroundColor Green
} finally {
    Pop-Location
}
